[phases.setup]
nixPkgs = ["python311", "nodejs_20", "libGL"]
aptPkgs = ["libglib2.0-0"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"